# Generated by Django 5.1.3 on 2024-12-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. Letters and digits only.', max_length=150, unique=True),
        ),
    ]
